/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import imagenes.ImagenFondo;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;
import objetoNegocio.Categoria;
import objetoNegocio.Producto;
import objetoNegocio.Proveedor;
import repositories.ProveedorRepository;

/**
 *
 * @author Estefanía Aguilar
 */
public class FmProveedor extends javax.swing.JFrame {
    ProveedorRepository proveedorRepository;
    /**
     * Creates new form FmProveedor
     */
    public FmProveedor(JFrame padre) {
        initComponents();
        this.setTitle("Proveedor");
        this.setLocationRelativeTo(null);
        this.proveedorRepository = new ProveedorRepository();
//        this.setSize(530,666);
        this.cargarTabla();
        //Imagen de fondo
//        try {
//            ImagenFondo fondo = new ImagenFondo(ImageIO.read(new File("C:/Users/laura/PuntoDeVentas/src/imagenes/blancoconcuadros.jpg")));
//            JPanel panel = (JPanel) this.getContentPane();
//            panel.setBorder(fondo);
//        } catch (IOException ex) {
//            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
//        };
//        
        txtID.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblID = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        lbRFC = new javax.swing.JLabel();
        lbDireccion = new javax.swing.JLabel();
        lbTelefono = new javax.swing.JLabel();
        lbPaginaWeb = new javax.swing.JLabel();
        txtPaginaWeb = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbProveedores = new javax.swing.JTable();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        txtRFC = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(608, 660));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblID.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        lblID.setText("ID");
        getContentPane().add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        lbNombre.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        lbNombre.setText("NOMBRE");
        getContentPane().add(lbNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        lbRFC.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        lbRFC.setText("RFC");
        getContentPane().add(lbRFC, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        lbDireccion.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        lbDireccion.setText("DIRECCIÓN");
        getContentPane().add(lbDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        lbTelefono.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        lbTelefono.setText("TELEFONO");
        getContentPane().add(lbTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        lbPaginaWeb.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        lbPaginaWeb.setText("PAGINA WEB");
        getContentPane().add(lbPaginaWeb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        txtPaginaWeb.setFont(new java.awt.Font("Calibri Light", 0, 22)); // NOI18N
        txtPaginaWeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaginaWebActionPerformed(evt);
            }
        });
        getContentPane().add(txtPaginaWeb, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 230, 30));

        txtNombre.setFont(new java.awt.Font("Calibri Light", 0, 22)); // NOI18N
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 230, 30));

        txtDireccion.setFont(new java.awt.Font("Calibri Light", 0, 22)); // NOI18N
        getContentPane().add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 230, 30));

        txtTelefono.setFont(new java.awt.Font("Calibri Light", 0, 22)); // NOI18N
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 230, 30));

        tbProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "RFC", "NOMBRE", "DIRECCION", "TELEFONO", "PAGINA WEB"
            }
        ));
        tbProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbProveedoresMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbProveedores);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 540, 170));

        btnCancelar.setFont(new java.awt.Font("Calibri Light", 0, 22)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 110, 30));

        btnGuardar.setFont(new java.awt.Font("Calibri Light", 0, 22)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 110, 30));

        txtRFC.setFont(new java.awt.Font("Calibri Light", 0, 22)); // NOI18N
        getContentPane().add(txtRFC, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 230, 30));

        txtID.setFont(new java.awt.Font("Calibri Light", 0, 22)); // NOI18N
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 230, 30));

        btnEliminar.setFont(new java.awt.Font("Calibri Light", 0, 22)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, 110, 30));

        btnMenu.setBackground(new java.awt.Color(255, 255, 255));
        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/casita.jpg"))); // NOI18N
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, -1, -1));

        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 580, 320));

        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 580, 50));

        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 580, 210));

        jLabel1.setFont(new java.awt.Font("Calibri Light", 3, 24)); // NOI18N
        jLabel1.setText("REGISTRO DE PROVEEDORES");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        guardar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void tbProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbProveedoresMouseClicked
        mostrarInfo();
        btnGuardar.setText("Editar");
    }//GEN-LAST:event_tbProveedoresMouseClicked

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        Menu menu = new Menu();
        menu.show();
        setVisible(false);
    }//GEN-LAST:event_btnMenuActionPerformed

    private void txtPaginaWebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaginaWebActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaginaWebActionPerformed
    private void guardar(){
        if(btnGuardar.getText().equalsIgnoreCase("Editar")){
            txtNombre.setEnabled(true);
            txtRFC.setEnabled(true);
            txtDireccion.setEnabled(true);
            txtTelefono.setEnabled(true);
            txtPaginaWeb.setEnabled(true);
            btnGuardar.setText("Actualizar");
            
        }else if(btnGuardar.getText().equalsIgnoreCase("Actualizar") && 
                !txtID.getText().isEmpty() && !txtNombre.getText().isEmpty() && !txtRFC.getText().isEmpty() && 
                !txtDireccion.getText().isEmpty()){
            
            //Se actualiza en la base de datos
            proveedorRepository.actualizar(new Proveedor(Long.parseLong(txtID.getText()), txtRFC.getText(), txtNombre.getText(), txtDireccion.getText(), 
                    txtTelefono.getText(), txtPaginaWeb.getText()));
            limpiar();
            
            txtNombre.setBorder(txtID.getBorder());
            txtRFC.setBorder(txtID.getBorder());
            txtDireccion.setBorder(txtID.getBorder());
            
        //Validar que todos los campos esten llenos    
        }else if(txtID.getText().isEmpty() && !txtNombre.getText().isEmpty() && !txtRFC.getText().isEmpty() && 
                !txtDireccion.getText().isEmpty()){
            
            //Guardar en la base de datos
            proveedorRepository.guardar(new Proveedor(txtRFC.getText(), txtNombre.getText(), txtDireccion.getText(), txtTelefono.getText(), txtPaginaWeb.getText())); 
            
            txtNombre.setBorder(txtID.getBorder());
            txtRFC.setBorder(txtID.getBorder());
            txtDireccion.setBorder(txtID.getBorder());
            
            limpiar();
            
        }else {
            //Todos los campos son obligatorios
            JOptionPane.showMessageDialog(this, "Llenar campos obligatorios", "Alerta", JOptionPane.WARNING_MESSAGE);
            LineBorder border = new LineBorder(Color.red);
            if (txtNombre.getText().isEmpty()) {
                txtNombre.setBorder(border);
            } else if (txtDireccion.getText().isEmpty()) {
                txtDireccion.setBorder(border);
            } else {
                txtRFC.setBorder(border);
            }
            
        }
        this.cargarTabla();
    }
    
    private void eliminar(){
        int indiceFila = tbProveedores.getSelectedRow();
        if(indiceFila == -1){
            JOptionPane.showMessageDialog(this, "Debes seleccionar una producto", "Información", JOptionPane.ERROR_MESSAGE);
        }else{
            Long proveedor = (Long)tbProveedores.getValueAt(indiceFila, 0);
            proveedorRepository.eliminar(proveedor);
            limpiar();
            cargarTabla();
        }
    }
     private void mostrarInfo(){
        int indiceFila = tbProveedores.getSelectedRow();
        Long idProveedor = (Long)tbProveedores.getValueAt(indiceFila, 0);
            Proveedor proveedor = proveedorRepository.buscarPorId(idProveedor);
            
            txtID.setText(String.valueOf(proveedor.getId()));
            txtNombre.setText(proveedor.getNombre());
            txtRFC.setText(proveedor.getRfc());
            txtDireccion.setText(proveedor.getDireccion());
            txtTelefono.setText(proveedor.getTelefono());
            txtPaginaWeb.setText(proveedor.getPaginaWeb());
            
            txtNombre.setEnabled(false);
            txtRFC.setEnabled(false);
            txtDireccion.setEnabled(false);
            txtTelefono.setEnabled(false);
            txtPaginaWeb.setEnabled(false);
    }
    
    private void limpiar(){
        txtID.setText("");
        txtNombre.setText("");;
        txtRFC.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtPaginaWeb.setText("");
        txtNombre.setEnabled(true);
        txtRFC.setEnabled(true);
        txtDireccion.setEnabled(true);
        txtTelefono.setEnabled(true);
        txtPaginaWeb.setEnabled(true);
        btnGuardar.setText("Guardar");
    }    
    
    private void cargarTabla(){
        ArrayList<Proveedor> proveedores = proveedorRepository.buscarTodas();        
        DefaultTableModel modelo = (DefaultTableModel)tbProveedores.getModel();        
        modelo.setRowCount(0);
        for (Proveedor proveedor: proveedores) {
            Object[] fila = new Object[8];
            fila[0] = proveedor.getId();
            fila[2] = proveedor.getNombre();
            fila[1] = proveedor.getRfc();
            fila[3] = proveedor.getDireccion();
            fila[4] = proveedor.getTelefono();
            fila[5] = proveedor.getPaginaWeb();
            modelo.addRow(fila);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbDireccion;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbPaginaWeb;
    private javax.swing.JLabel lbRFC;
    private javax.swing.JLabel lbTelefono;
    private javax.swing.JLabel lblID;
    private javax.swing.JTable tbProveedores;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPaginaWeb;
    private javax.swing.JTextField txtRFC;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
